### ISSUE TITLE
Issues with PubSub emulator

### ISSUE THREAD

**Issue by jdinartejesus** [aVigorousDev/docker-firebase-cli#1]
I'm currently using this image with docker-compose, but I'm having error when adding pubsub to the firebase.json.

Firebase.json
```
{
  "emulators": {
    "auth": {
      "host": "0.0.0.0",
      "port": 9001
    },
    "database": {
      "host": "0.0.0.0",
      "port": 9002
    },
    "functions": {
      "host": "0.0.0.0",
      "port": 9003
    },
    "pubsub": {
      "host": "0.0.0.0",
      "port": 8085
    },
    "ui": {
      "enabled": true,
      "host": "0.0.0.0",
      "port": 9004
    }
  }
}
```

Error on Docker:
```
pubsub: Fatal error occurred: 
Pub/Sub Emulator has exited with code: 127,
```

pubsub-debug.log:
```
env: can't execute 'bash': No such file or directory
```

**Comment by davidmyersdev** [comment]
Hey @jdinartejesus! Thanks for raising this issue. I'll attempt to replicate this on my end, but do you happen to have a full example you can share?

**Comment by davidmyersdev** [comment]
Fixed in 0c24a6691aa1ef2ee3b5e1d83fecb2201eb00890. I just tagged `v1.2.0`, but let me know if you run into any more issues!

**Comment by jdinartejesus** [comment]
Hi @voraciousdev that was the fastest issue being solved so far for me on Open Source!

Thanks so much for solving and for the useful repo. 🙏

**Comment by davidmyersdev** [comment]
I'm glad I could help, @jdinartejesus! 😁
