### ISSUE TITLE
Enable data Presistence for Firebase emulator

### ISSUE THREAD

**Issue by jdinartejesus** [aVigorousDev/docker-firebase-cli#2]
Hi @voraciousdev, I'm currently looking to have persistent data to avoid creating new users or data all the time for testing. I saw there's already an option in firebase, do you think would make sense to have it here too?

https://github.com/firebase/firebase-tools/issues/2269

**Comment by davidmyersdev** [comment]
@jdinartejesus that looks like a great feature to add. I'll add it to the list. 👍

**Comment by jdinartejesus** [comment]
Thanks @voraciousdev, how would you recommend implementing now? I'm trying to set up this currently but not sure what's the best way using this package.

**Comment by davidmyersdev** [comment]
@jdinartejesus I think a good approach will be to allow a custom startup script when running the container. I'll see if I can get this updated tonight or tomorrow!

**Comment by jdinartejesus** [comment]
Ah that's actually a good idea, let me know if you had a chance to take a look.

**Comment by davidmyersdev** [comment]
@jdinartejesus I have started on it, but I've been away for work the last few days. I'll be home tomorrow, and I hope to get it finished up once I'm back!

**Comment by davidmyersdev** [comment]
Hey @jdinartejesus. I was finally able to get this working locally, so I just released a new version. You _might_ have to create an initial export manually (see below), but then it should automatically import/export going forward.

```sh
docker exec -it firebase --project $PROJECT_ID --non-interactive emulators:export -f ./data
```

**Comment by jdinartejesus** [comment]
Sorry, only saw it now! That's so awesome, thanks so much for working on it @voraciousdev 🎉

**Comment by davidmyersdev** [comment]
@jdinartejesus no problem! Let me know if you run into any issues!

**Comment by jdinartejesus** [comment]
Hi @voracious sorry for the late reply but everything worked, I just had to do some changes in your exporting command: 

```
docker exec -it $CONTAINER firebase --project $PROJECT_ID  --non-interactive emulators:export -f ./data
```

**Comment by davidmyersdev** [comment]
Hey @jdinartejesus! I'm glad it worked out, and thanks for following up!
